[package]
name = "ecl2hdf"
version = "0.1.0"
authors = ["Yan <mindv0rtex@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
arrayvec = "0.5"
byteorder = "1.3"
itertools = "0.9"
phf = { version = "0.8", features = ["macros"] }
rmp = "0.8"
structopt = "0.3"
thiserror = "1.0"

[profile.release]
panic = 'abort'